"""
SmartHire Adaptive Interview Engine.

Phase 4F responsibilities:

- Analyze the latest interview evaluation.
- Identify the candidate's weakest demonstrated dimension.
- Decide whether to reinforce, maintain, or increase difficulty.
- Select the next interview strategy.
- Generate the next personalized question using the existing LLM Gateway.
- Return structured data ready for API persistence.

The adaptive engine controls the interview strategy.
The LLM generates the actual question content.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from backend.services.llm.gateway import LLMGateway


logger = logging.getLogger(
    "smarthire.interview.adaptive"
)


# ============================================================
# CONSTANTS
# ============================================================

VALID_CATEGORIES = {
    "technical",
    "behavioral",
    "project",
    "problem_solving",
    "system_design",
    "coding",
}

VALID_DIFFICULTIES = {
    "easy",
    "medium",
    "hard",
}


DIFFICULTY_ORDER = {
    "easy": 0,
    "medium": 1,
    "hard": 2,
}


# Scores below this indicate a clear weakness.
WEAK_SCORE_THRESHOLD = 60

# Scores at or above this indicate strong performance.
STRONG_SCORE_THRESHOLD = 85


# ============================================================
# PYDANTIC MODELS
# ============================================================

class AdaptiveDecision(BaseModel):
    """
    Deterministic decision describing what the next question
    should accomplish.
    """

    strategy: str = Field(
        ...,
        min_length=1,
        max_length=100,
    )

    focus_dimension: str = Field(
        ...,
        min_length=1,
        max_length=100,
    )

    focus_skill: str = Field(
        default="",
        max_length=200,
    )

    next_category: str = Field(
        ...,
        min_length=1,
        max_length=50,
    )

    next_difficulty: str = Field(
        ...,
        min_length=1,
        max_length=20,
    )

    reason: str = Field(
        ...,
        min_length=1,
        max_length=1000,
    )

    priority: str = Field(
        ...,
        min_length=1,
        max_length=30,
    )


class AdaptiveQuestion(BaseModel):
    """
    Structured next question generated by the LLM.
    """

    question: str = Field(
        ...,
        min_length=10,
        max_length=3000,
    )

    category: str = Field(
        ...,
        min_length=1,
        max_length=50,
    )

    difficulty: str = Field(
        ...,
        min_length=1,
        max_length=20,
    )

    skill: str = Field(
        default="",
        max_length=200,
    )

    expected_topics: List[str] = Field(
        default_factory=list,
    )

    @field_validator("question", mode="before")
    @classmethod
    def clean_question(cls, value: Any) -> str:
        value = str(value or "").strip()

        if not value:
            raise ValueError(
                "Generated question cannot be empty."
            )

        return value

    @field_validator(
        "expected_topics",
        mode="before",
    )
    @classmethod
    def clean_topics(
        cls,
        value: Any,
    ) -> List[str]:

        if value is None:
            return []

        if not isinstance(value, list):
            value = [value]

        cleaned: List[str] = []

        for item in value:
            text = str(item or "").strip()

            if text and text.lower() not in {
                existing.lower()
                for existing in cleaned
            }:
                cleaned.append(text)

        return cleaned[:10]


class AdaptiveResult(BaseModel):
    """
    Complete Phase 4F result.
    """

    decision: AdaptiveDecision
    question: AdaptiveQuestion


# ============================================================
# ENGINE
# ============================================================

class AdaptiveInterviewEngine:
    """
    Controls adaptive interview behavior.

    Important design principle:

        deterministic rules -> adaptive decision
        LLM                   -> question generation

    The LLM does not decide interview state or scoring thresholds.
    """

    def __init__(
        self,
        provider: str = "groq",
    ):
        self.gateway = LLMGateway(
            provider=provider
        )

    # ========================================================
    # PUBLIC METHOD
    # ========================================================

    async def generate_next_question(
        self,
        *,
        current_question: str,
        current_category: str,
        current_difficulty: str,
        current_skill: str,
        current_expected_topics: List[str],
        technical_score: int,
        relevance_score: int,
        clarity_score: int,
        depth_score: int,
        role: str = "",
        job_description: str = "",
        previous_question_numbers: Optional[List[int]] = None,
        previous_questions: Optional[List[str]] = None,
        candidate_answer: str = "",
    ) -> AdaptiveResult:
        """
        Analyze the latest evaluation and generate the next
        adaptive interview question.
        """

        decision = self._build_adaptive_decision(
            current_category=current_category,
            current_difficulty=current_difficulty,
            current_skill=current_skill,
            technical_score=technical_score,
            relevance_score=relevance_score,
            clarity_score=clarity_score,
            depth_score=depth_score,
        )

        prompt = self._build_question_prompt(
            decision=decision,
            current_question=current_question,
            current_category=current_category,
            current_difficulty=current_difficulty,
            current_skill=current_skill,
            current_expected_topics=current_expected_topics,
            candidate_answer=candidate_answer,
            role=role,
            job_description=job_description,
            previous_questions=previous_questions or [],
        )

        try:
            raw_result = await self.gateway.generate_json(
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are SmartHire's adaptive "
                            "interviewer. Generate exactly one "
                            "high-quality interview question. "
                            "Return only valid JSON."
                        ),
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ]
            )

        except Exception as exc:
            logger.exception(
                "Adaptive question generation failed."
            )

            raise RuntimeError(
                "Adaptive question generation failed."
            ) from exc

        question = self._validate_question(
            raw_result,
            decision=decision,
        )

        return AdaptiveResult(
            decision=decision,
            question=question,
        )

    # ========================================================
    # ADAPTIVE DECISION
    # ========================================================

    def _build_adaptive_decision(
        self,
        *,
        current_category: str,
        current_difficulty: str,
        current_skill: str,
        technical_score: int,
        relevance_score: int,
        clarity_score: int,
        depth_score: int,
    ) -> AdaptiveDecision:

        scores = {
            "technical": technical_score,
            "relevance": relevance_score,
            "clarity": clarity_score,
            "depth": depth_score,
        }

        weakest_dimension = min(
            scores,
            key=scores.get,
        )

        weakest_score = scores[
            weakest_dimension
        ]

        overall_score = round(
            technical_score * 0.35
            + relevance_score * 0.25
            + clarity_score * 0.15
            + depth_score * 0.25
        )

        next_difficulty = self._choose_difficulty(
            current_difficulty=current_difficulty,
            overall_score=overall_score,
        )

        # ----------------------------------------------------
        # Weak performance
        # ----------------------------------------------------

        if weakest_score < WEAK_SCORE_THRESHOLD:

            if weakest_dimension == "technical":
                return AdaptiveDecision(
                    strategy="targeted_technical_follow_up",
                    focus_dimension="technical",
                    focus_skill=current_skill,
                    next_category=self._technical_category(
                        current_category
                    ),
                    next_difficulty=next_difficulty,
                    reason=(
                        f"Technical performance was "
                        f"{weakest_score}/100. The next question "
                        f"should probe the same skill more deeply "
                        f"with a practical or conceptual follow-up."
                    ),
                    priority="high",
                )

            if weakest_dimension == "depth":
                return AdaptiveDecision(
                    strategy="depth_follow_up",
                    focus_dimension="depth",
                    focus_skill=current_skill,
                    next_category=current_category
                    if current_category in VALID_CATEGORIES
                    else "technical",
                    next_difficulty=next_difficulty,
                    reason=(
                        f"Answer depth was "
                        f"{weakest_score}/100. The next question "
                        f"should require reasoning, trade-offs, "
                        f"examples, or implementation details."
                    ),
                    priority="high",
                )

            if weakest_dimension == "relevance":
                return AdaptiveDecision(
                    strategy="relevance_application",
                    focus_dimension="relevance",
                    focus_skill=current_skill,
                    next_category=(
                        "problem_solving"
                        if current_category != "behavioral"
                        else "behavioral"
                    ),
                    next_difficulty=next_difficulty,
                    reason=(
                        f"Relevance was "
                        f"{weakest_score}/100. The next question "
                        f"should make the candidate apply the "
                        f"concept directly to a realistic scenario."
                    ),
                    priority="high",
                )

            return AdaptiveDecision(
                strategy="clarity_follow_up",
                focus_dimension="clarity",
                focus_skill=current_skill,
                next_category=current_category
                if current_category in VALID_CATEGORIES
                else "behavioral",
                next_difficulty=next_difficulty,
                reason=(
                    f"Clarity was {weakest_score}/100. "
                    "The next question should encourage a "
                    "structured explanation with clear reasoning."
                ),
                priority="medium",
            )

        # ----------------------------------------------------
        # Strong performance
        # ----------------------------------------------------

        if overall_score >= STRONG_SCORE_THRESHOLD:

            return AdaptiveDecision(
                strategy="increase_difficulty",
                focus_dimension="overall",
                focus_skill=current_skill,
                next_category=self._advance_category(
                    current_category
                ),
                next_difficulty=self._increase_difficulty(
                    current_difficulty
                ),
                reason=(
                    f"The candidate demonstrated strong "
                    f"overall performance ({overall_score}/100). "
                    "Increase challenge while remaining relevant "
                    "to the target role."
                ),
                priority="medium",
            )

        # ----------------------------------------------------
        # Normal performance
        # ----------------------------------------------------

        return AdaptiveDecision(
            strategy="reinforce_and_progress",
            focus_dimension=weakest_dimension,
            focus_skill=current_skill,
            next_category=current_category
            if current_category in VALID_CATEGORIES
            else "technical",
            next_difficulty=current_difficulty
            if current_difficulty in VALID_DIFFICULTIES
            else "medium",
            reason=(
                f"Overall performance was {overall_score}/100. "
                f"The weakest dimension was "
                f"{weakest_dimension} at "
                f"{weakest_score}/100. Continue at the current "
                "difficulty while reinforcing that area."
            ),
            priority="medium",
        )

    # ========================================================
    # DIFFICULTY
    # ========================================================

    @staticmethod
    def _choose_difficulty(
        *,
        current_difficulty: str,
        overall_score: int,
    ) -> str:

        difficulty = (
            current_difficulty.lower().strip()
            if current_difficulty
            else "medium"
        )

        if difficulty not in VALID_DIFFICULTIES:
            difficulty = "medium"

        if overall_score < 45:
            return "easy"

        if overall_score < 75:
            return difficulty

        if overall_score >= 85:
            return AdaptiveInterviewEngine._increase_difficulty(
                difficulty
            )

        return difficulty

    @staticmethod
    def _increase_difficulty(
        difficulty: str,
    ) -> str:

        current = DIFFICULTY_ORDER.get(
            difficulty,
            1,
        )

        next_level = min(
            current + 1,
            2,
        )

        for name, value in DIFFICULTY_ORDER.items():
            if value == next_level:
                return name

        return "hard"

    # ========================================================
    # CATEGORY
    # ========================================================

    @staticmethod
    def _technical_category(
        current_category: str,
    ) -> str:

        if current_category == "coding":
            return "coding"

        if current_category == "system_design":
            return "system_design"

        return "technical"

    @staticmethod
    def _advance_category(
        current_category: str,
    ) -> str:

        progression = {
            "technical": "problem_solving",
            "problem_solving": "system_design",
            "coding": "system_design",
            "system_design": "project",
            "project": "technical",
            "behavioral": "problem_solving",
        }

        return progression.get(
            current_category,
            "technical",
        )

    # ========================================================
    # PROMPT
    # ========================================================

    def _build_question_prompt(
        self,
        *,
        decision: AdaptiveDecision,
        current_question: str,
        current_category: str,
        current_difficulty: str,
        current_skill: str,
        current_expected_topics: List[str],
        candidate_answer: str,
        role: str,
        job_description: str,
        previous_questions: List[str],
    ) -> str:

        topics_text = "\n".join(
            f"- {topic}"
            for topic in current_expected_topics
            if topic
        )

        if not topics_text:
            topics_text = "- No explicit topics."

        previous_text = "\n".join(
            f"- {question}"
            for question in previous_questions[-10:]
            if question
        )

        if not previous_text:
            previous_text = "- No previous questions available."

        jd_text = (
            job_description[:8000]
            if job_description
            else "No job description provided."
        )

        answer_text = (
            candidate_answer[:6000]
            if candidate_answer
            else "Candidate answer unavailable."
        )

        return f"""
You are generating the NEXT question in an adaptive
technical interview.

============================================================
TARGET ROLE
============================================================

{role or "Not specified."}

============================================================
JOB DESCRIPTION
============================================================

{jd_text}

============================================================
LATEST QUESTION
============================================================

Question:
{current_question}

Category:
{current_category}

Difficulty:
{current_difficulty}

Skill:
{current_skill or "Not specified."}

Expected topics:
{topics_text}

============================================================
LATEST CANDIDATE ANSWER
============================================================

{answer_text}

============================================================
ADAPTIVE DECISION
============================================================

Strategy:
{decision.strategy}

Focus dimension:
{decision.focus_dimension}

Focus skill:
{decision.focus_skill or "Same relevant skill"}

Next category:
{decision.next_category}

Next difficulty:
{decision.next_difficulty}

Priority:
{decision.priority}

Reason:
{decision.reason}

============================================================
PREVIOUS QUESTIONS
============================================================

{previous_text}

============================================================
QUESTION GENERATION RULES
============================================================

1. Generate exactly ONE question.

2. Follow the adaptive strategy.

3. The question must be relevant to the target role.

4. Do not repeat the latest question.

5. Do not repeat a previous question.

6. If the candidate was weak technically, test the same
   underlying skill using a different angle.

7. If depth was weak, ask for reasoning, trade-offs,
   implementation details, or a realistic scenario.

8. If relevance was weak, ask an application-oriented
   question.

9. If clarity was weak, ask a question that naturally
   encourages a structured explanation.

10. If the candidate performed strongly, increase the
    conceptual or practical challenge.

11. Do not invent experience that the candidate did not
    demonstrate.

12. For project questions, refer only to projects or
    technologies actually present in the supplied context.

13. Keep the question answerable in an interview setting.

14. Do not ask multiple unrelated questions.

15. Return VALID JSON only.

============================================================
REQUIRED JSON
============================================================

{{
  "question": "One interview question",
  "category": "{decision.next_category}",
  "difficulty": "{decision.next_difficulty}",
  "skill": "{decision.focus_skill or current_skill}",
  "expected_topics": [
    "topic 1",
    "topic 2",
    "topic 3"
  ]
}}

Return JSON now.
"""

    # ========================================================
    # VALIDATION
    # ========================================================

    @staticmethod
    def _validate_question(
        raw_result: Any,
        *,
        decision: AdaptiveDecision,
    ) -> AdaptiveQuestion:

        if isinstance(raw_result, str):
            raw_result = raw_result.strip()

            try:
                raw_result = json.loads(
                    raw_result
                )
            except json.JSONDecodeError as exc:
                raise ValueError(
                    "Adaptive interviewer returned invalid JSON."
                ) from exc

        if not isinstance(raw_result, dict):
            raise ValueError(
                "Adaptive interviewer must return a JSON object."
            )

        if not raw_result.get("question"):
            raise ValueError(
                "Adaptive interviewer returned an empty question."
            )

        # The strategy controls these fields.
        # Do not allow the LLM to silently change the
        # adaptive decision.
        raw_result["category"] = (
            decision.next_category
        )

        raw_result["difficulty"] = (
            decision.next_difficulty
        )

        if not raw_result.get("skill"):
            raw_result["skill"] = (
                decision.focus_skill
            )

        try:
            return AdaptiveQuestion(
                **raw_result
            )

        except Exception as exc:
            logger.exception(
                "Adaptive question failed validation."
            )

            raise ValueError(
                "Adaptive question returned invalid data."
            ) from exc